# Generated by Django 4.1.1 on 2022-10-27 20:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название категории', max_length=100, verbose_name='nameCat')),
                ('description', models.TextField(help_text='Описание категории', max_length=1000, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Categories',
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название изделия', max_length=100, verbose_name='nameProd')),
                ('description', models.TextField(help_text='Описание изделия', max_length=1000, verbose_name='description')),
                ('cost', models.IntegerField(help_text='Цена', verbose_name='cost')),
                ('category', models.ForeignKey(help_text='ID категории', on_delete=django.db.models.deletion.CASCADE, to='myapp.categories', verbose_name='category')),
            ],
            options={
                'verbose_name': 'Products',
                'db_table': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay', models.CharField(choices=[('MONEY', 'Наличными'), ('CARD', 'Картой')], default='CARD', help_text='Вид оплаты', max_length=5)),
                ('orderDate', models.DateTimeField(default=datetime.datetime.now, help_text='Дата заказа')),
                ('products', models.ManyToManyField(to='myapp.products')),
                ('user', models.ForeignKey(help_text='ID пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orders',
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='CreativeProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название изделия', max_length=100, verbose_name='nameProd')),
                ('category', models.ForeignKey(help_text='ID категории', on_delete=django.db.models.deletion.CASCADE, to='myapp.categories', verbose_name='category')),
            ],
            options={
                'verbose_name': 'CreativeProducts',
                'db_table': 'CreativeProducts',
            },
        ),
        migrations.CreateModel(
            name='CreativeOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Адрес электронной почты', max_length=30, verbose_name='email')),
                ('typeOfWood', models.CharField(choices=[('PINE', 'Сосна'), ('SPRUCE', 'Ель'), ('ASPEN', 'Осина'), ('BIRCH', 'Береза'), ('BEECH', 'Бук'), ('OAK', 'Дуб'), ('ELM', 'Вяз'), ('MAPLE', 'Клен'), ('ASH', 'Ясень')], default='OAK', help_text='Вид древисины', max_length=6)),
                ('techTask', models.TextField(help_text='Описание пожеланий к изделию', max_length=1000, verbose_name='techTask')),
                ('exampleImg', models.ImageField(help_text='Чертеж или эскиз', upload_to='uploads/', verbose_name='image')),
                ('orderDate', models.DateTimeField(default=datetime.datetime.now, help_text='Дата заказа')),
                ('user', models.ForeignKey(help_text='ID пользователя', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CreativeOrders',
                'db_table': 'CreativeOrders',
            },
        ),
    ]
