# Generated by Django 4.1.1 on 2022-11-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_categories_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='ownCost',
            field=models.IntegerField(default=0, help_text='Себестоимость', verbose_name='ownCost'),
        ),
        migrations.AddField(
            model_name='products',
            name='weight',
            field=models.IntegerField(default=0, help_text='Вес', verbose_name='weight'),
        ),
    ]
