# Generated by Django 4.1.1 on 2022-12-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_creativeorders_exampleimg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeorders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 9, 30, 44, 955518, tzinfo=datetime.timezone.utc), help_text='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='creativeorders',
            name='typeOfWood',
            field=models.CharField(choices=[('PINE', 'Сосна'), ('SPRUCE', 'Ель'), ('ASPEN', 'Осина'), ('BIRCH', 'Береза'), ('BEECH', 'Бук'), ('OAK', 'Дуб'), ('ELM', 'Вяз'), ('MAPLE', 'Клен'), ('ASH', 'Ясень')], default='OAK', help_text='Вид древесины', max_length=6),
        ),
    ]
