# Generated by Django 4.1.1 on 2023-02-22 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_creativeorders_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeorders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 6, 51, 9, 48526, tzinfo=datetime.timezone.utc), help_text='Дата заказа'),
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='creativeorders',
            table='creativeOrders',
        ),
        migrations.AlterModelTable(
            name='creativeproducts',
            table='creativeProducts',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='orders',
        ),
        migrations.AlterModelTable(
            name='products',
            table='products',
        ),
    ]
