# Generated by Django 4.1.1 on 2023-02-22 06:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_creativeorders_orderdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeorders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 6, 51, 58, 846339, tzinfo=datetime.timezone.utc), help_text='Дата заказа'),
        ),
    ]
