# Generated by Django 4.1.1 on 2023-02-22 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_creativeorders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeorders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 7, 7, 44, 631375, tzinfo=datetime.timezone.utc), help_text='Дата заказа'),
        ),
    ]
