# Generated by Django 4.1.1 on 2023-02-22 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_creativeorders_orderdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creativeorders',
            name='orderDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 22, 8, 29, 1, 887216, tzinfo=datetime.timezone.utc), help_text='Дата заказа'),
        ),
        migrations.AlterModelTable(
            name='creativeorders',
            table='creativeorders',
        ),
        migrations.AlterModelTable(
            name='creativeproducts',
            table='creativeproducts',
        ),
    ]
